//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookEntity
    {
        public int bookID { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    }
}
